### ISSUE TITLE
Compressed creativity encountered an issue

### ISSUE THREAD

**Issue by 78codemonkey** [Lgmrszd/CompressedCreativity#15]
forge 40.1.87 mc 1.18.2, create 5g
Compressed creativity 0.1.2 & 0.1.3
![Minecraft_ 1 18 2 12_18_2022 9_31_40 PM](https://user-images.githubusercontent.com/22382220/208342898-16ea1615-f1d2-4cbc-bbec-552cd5000286.png)

**Comment by Lgmrszd** [comment]
Thanks, I'll look into it

**Comment by nphhpn** [comment]
I also encountered that issue. From the crash log, the problem is this:
`java.lang.IncompatibleClassChangeError: class com.lgmrszd.compressedcreativity.blocks.air_blower.AirBlowerTileEntity overrides final method com.simibubi.create.foundation.tileEntity.SmartTileEntity.m_7651_()V`

It seems like latest Create update made `SmartTileEntity.setRemoved` final and move the unloading handling to `SmartTileEntity.invalidate`

**Comment by Lgmrszd** [comment]
Yep, that was the problem. Already moved invalidation of capabilities to other method (as well as added it in other blocks that missed it oops), will be releasing soon with the content update!

**Comment by 78codemonkey** [comment]
awesome :)

**Comment by Proxwian** [comment]
Please we need it asap(

**Comment by Proxwian** [comment]
Do you have ETA on release?

**Comment by Lgmrszd** [comment]
I have ETA and the ETA is now! :D
