### ISSUE TITLE
Uses of the Dense Mesh and the Frozen Mesh

### ISSUE THREAD

**Issue by Pixl64** [Lgmrszd/CompressedCreativity#31]
I don't see the reason behind using the dense mesh, as smelting and smoking can be performed without the mesh. I also don't know what the frozen mesh it used for, as I expected it to possibly convert ice or something but nothing happened. It would also make sense to be given the frozen effect when in the frozen fan range, as all of the other fans perform some sort of effect on the player.

**Comment by Lgmrszd** [comment]
Meshes are just neat one block solutions for those who don't want lava/water on their setup (as well as campfires)
Frozen mesh is literally what happens if you for some reason cool down the soaked mesh below 0°C, it's here just for fun. Having freezing Air Current would be cool to be honest but sadly Create doesn't provide a way to add custom ones, you can only have smoking/blasting/washing/haunting.

**Comment by Pixl64** [comment]
Oh ok that makes sense, thanks for the reply
